[project]
name = "codingagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beanie>=2.1.0",
    "cryptography>=48.0.1",
    "fastapi>=0.115.0",
    "langchain>=1.3.4",
    "langchain-anthropic>=1.4.4",
    "langchain-openai>=1.2.2",
    "langfuse>=4.7.1",
    "langgraph>=1.2.4",
    "langgraph-checkpoint-mongodb>=0.4.0",
    "pydantic-settings>=2.14.1",
    "pyjwt>=2.13.0",
    "pymongo>=4.16.0",
    "python-dotenv>=1.2.2",
    "uvicorn[standard]>=0.30.0",
]
